services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: symfony_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: ${SYMFONY_DATABASE_URL}
    networks:
      - app_network

  frontend:
    image: node:20-alpine
    container_name: vue_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    command: sh -c "npm install && npm run dev -- --host"


  webserver:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
